### ISSUE TITLE
Deleting Generated Files

### ISSUE THREAD

**Issue by bdoze90** [bdoze90/CASPERapp#11]
When the user quits the program there should be a dialog prompt asking if they want to save the files that have been downloaded during the session.  These file paths should be stored in a list in Global_Settings.py.  So every time a .fasta, feature_table, .gff, is downloaded or a .cspr file is generated in NewGenome or in Cotargeting, the file path should be added to the Global_Settings.py list.  The dialog prompt should give them the option of selecting and deselecting files that the want to save and files that they want to delete.

**Comment by jherman1997** [comment]
With my latest push this enhancement is completed.

Once the program closes the program, a little window opens up that lists all of the files in the CSPR_DB folder. User selects whichever ones they want(multiple or none) and hits submit. Files selected are deleted. If no files are selected, the program just closes without doing anything.

Currently this code is called from 4 classes: mainWindow, annotationsWindow, results, and multitargetting.
