### ISSUE TITLE
Find Targets without Show all results does not initialize view targets

### ISSUE THREAD

**Issue by bdoze90** [bdoze90/CASPERapp#4]
If the show all results check box is not selected then the annotation window is never called and then it can't pass data to the Results class.  Create an if statement on the show all results such that if it is not selected pass every single result from the search into view targets.  Perhaps make a warning if the search results return over say 50 values that it may be loading a ton of data and does the user really wish to continue.

**Comment by jherman1997** [comment]
Fixed the issue. 
Called collect_table_data after marking each piece of data for showing
Also put in a warning for the user if there were more than 15 matches
