### ISSUE TITLE
Put Co-targeting and switching Endonuclease in Results window

### ISSUE THREAD

**Issue by bdoze90** [bdoze90/CASPERapp#6]
In the Results window there should be an option to switch the endonuclease. This information can be pulled from the CRISPRdb folder similar to how the dropdown list in the main window is generated.  The difference here is that the organism does not change so the file has to have the same organism code (e.g. yli).  If the endonuclease is switched, a new set of targets will be generated using all the same information as before (transfer_data function) but using the new .cspr file.
For example:
If they generated targets for Saccharomyces Cerevisiae S288C using spCas9 but wanted to switch to asCas12, they would select asCas12 from the dropdown menu and click a "switch endonuclease" button.  The results window would then repopulate the table with the information from sce_asCas12.cspr rather than the original sce_spCas9.cspr file.
This dropdown should replace the off-targets button.  Off-targets will be moved into the "Tools" dropdown menu.

**Comment by jherman1997** [comment]
With my latest push, I have added the 'change endonuclease' functionality to the Results window. 
I am not setting this issue as closed yet, since the Co-Targeting has not been added yet

**Comment by jherman1997** [comment]
With my latest push, a cotargeting button has been added to the Tools menu in Results. This just opens the cotargeting window the same way Main opens cotargeting. Results is not hidden, although that would be an easy change to implement.
