### ISSUE TITLE
Selecting NCBI annotation

### ISSUE THREAD

**Issue by bdoze90** [bdoze90/CASPERapp#9]
One of the 3 options for the user to select their annotation.  This one will pull from the NCBI ftp database either the annotation table or the gbff file.  The choice is up to the user (radio button).  The file that is downloaded will then be parsed using Josh's parsing code for annotation table and Brian's parsing code for gbff files.
Note: Start with just the "feature_table.txt" first and then move onto the gbff file since this will have to wait on Brian's code

**Comment by jherman1997** [comment]
Currently the user can download a GFF, GBFF, and a Feature Table from NCBI. 
If they download a GBFF file, nothing happens since we do not have that Parser.

**Comment by jherman1997** [comment]
The downloader is not working. There may be an issue with Entrez, but as it is right now, I do not know what the issue is.

**Comment by jherman1997** [comment]
After my last push the issue has been resolved, and the NCBI downloader now works. I also implemented a way such that the user can input the Return Max they want to set for the NCBI searcher, however the user cannot set a value larger than 100 for this number.
